services:
  catalogdb:
      container_name: catalogdb
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgress@2024
        POSTGRES_DB: CatalogDb
      ports:
          - "5432:5432"
      volumes:
        - postgres_catalog:/var/lib/postgresql/data
        
  basketdb:
    container_name: basketdb
    environment:
      POSTGRES_USER: basket
      POSTGRES_PASSWORD: basket@2024
      POSTGRES_DB: BasketDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data
      
  distributedcache:
    container_name: distributedcache
    image: redis
    ports:
      - "6379:6379"
      
  catalog.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
#        - ASPNETCORE_HTTPS_PORTS=8081 I need to found out how to install the development certificate
        - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgress@2024
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
#      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      
  basket.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
#        - ASPNETCORE_HTTPS_PORTS=8081 I need to found out how to install the development certificate
        - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=basket;Password=basket@2024
        - ConnectionStrings__Redis=distributedcache:6379
    depends_on:
      - basketdb
      - distributedcache
    ports:
      - "6001:8080"
#      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      
  discount.grpc:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ConnectionStrings__Database=Data Source=discountsdb    
    ports:
      - "6002:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro