services:
  catalogdb:
    image: postgres
    
  basketdb:
    image: postgres
    
  distributedcache:
    image: redis
    
  orderdb:
    image: mcr.microsoft.com/mssql/server
    
  messagebroker:
    image: rabbitmq:management
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
      
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountsgrpc
    build:
      context: .
      dockerfile: Services/Discounts/Discounts.Grpc/Dockerfile
    
volumes:
  postgres_catalog:
  postgres_basket: