services:
  catalogdb:
      container_name: catalogdb
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgress@2024
        POSTGRES_DB: CatalogDb
      ports:
          - "5432:5432"
      volumes:
        - postgres_catalog:/var/lib/postgresql/data
        
  basketdb:
    container_name: basketdb
    environment:
      POSTGRES_USER: basket
      POSTGRES_PASSWORD: basket@2024
      POSTGRES_DB: BasketDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data
      
  distributedcache:
    container_name: distributedcache
    image: redis
    ports:
      - "6379:6379"
  
  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: "sqlserver@2024"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"        
  
  messagebroker:
    container_name: ecommerce-mq
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
#      - ASPNETCORE_HTTPS_PORTS=8081 #I need to found out how to install the development certificate
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgress@2024
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
#      - "6060:8081"
    volumes:
#      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro #I don't have local secrets at the moment
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro
      
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
#      - ASPNETCORE_HTTPS_PORTS=8081 #I need to found out how to install the development certificate
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=basket;Password=basket@2024
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountsUrl=http://discount.grpc:8080
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
      - messagebroker
    ports:
      - "6001:8080"
#      - "6061:8081"
    volumes:
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro
      
  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Data Source=discountsdb    
    ports:
      - "6002:8080"
    volumes:
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro
  
  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
#      - ASPNETCORE_HTTPS_PORTS=8081 # I need to found out how to install the development certificate
      - ConnectionStrings__Database=Server=orderdb;Database=OrderDb;User Id=sa;Password=sqlserver@2024;Encrypt=False;TrustServerCertificate=True;
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFulfillment=false # Set to true to enable order fulfillment feature (shipping, etc.)
    depends_on:
      - orderdb
      - messagebroker
    ports:
      - "6003:8080"
#      - "6063:8081"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  apiGateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
#      - ASPNETCORE_HTTPS_PORTS=8081 #I need to found out how to install the development certificate
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "6004:8080"
#      - "6064:8081"
    volumes:
      - $HOME/.aspnet/https:/home/app/.aspnet/https:ro